version: '3.8'

services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile.dev
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./app/:/home/app/web
    ports:
      - '8000:8000'
    env_file:
      - ./.env.dev
    depends_on:
      - database
  
  database:
    image: 'postgres:14.1'
    ports:
      - '5432:5432'
    restart: always
    container_name: db
    env_file:
      - ./.env.dev.db
    volumes:
      - 'pg_data:/var/lib/postgresql/data:rw'
  redis:
    image: redis:6.2-alpine
    container_name: cache
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - cache:/data

volumes:
  pg_data:
  cache:
