# Generated by Django 4.1.1 on 2022-09-28 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Account",
        ),
    ]
