# Generated by Django 4.1.1 on 2022-09-30 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("account", "0002_delete_account"),
    ]

    operations = [
        migrations.AlterField(
            model_name="friends",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to=settings.AUTH_USER_MODEL,
                unique=True,
            ),
        ),
    ]
