# Generated by Django 4.1.1 on 2022-09-29 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "chat",
            "0002_group_groupmessage_usermessage_remove_chat_users_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="chat",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="chat.chat",
            ),
        ),
    ]
