# Generated by Django 4.1.1 on 2022-09-29 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_group_chat"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="groupmessage",
            name="read",
        ),
        migrations.RemoveField(
            model_name="usermessage",
            name="read",
        ),
    ]
