# Generated by Django 4.1.1 on 2022-09-30 00:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_remove_groupmessage_read_remove_usermessage_read"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupmessage",
            options={"ordering": ("timestamp",)},
        ),
    ]
