# Generated by Django 4.1.1 on 2022-09-30 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0005_alter_groupmessage_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="groupmessage",
            options={"ordering": ("-timestamp",)},
        ),
    ]
