# Generated by Django 4.1.1 on 2022-09-30 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_alter_groupmessage_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usermessage",
            options={"ordering": ("-timestamp",)},
        ),
    ]
